-- Dashboard Schema
-- Run this directly in your Supabase SQL Editor to activate the Dashboard tables!

-- 1. Vitals Table
CREATE TABLE IF NOT EXISTS public.vitals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metric TEXT NOT NULL,
  value TEXT NOT NULL,
  unit TEXT NOT NULL,
  recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

INSERT INTO public.vitals (metric, value, unit) VALUES
('Heart Rate', '72', 'bpm'),
('Blood Pressure', '120/80', 'mmHg'),
('Blood Sugar', '98', 'mg/dL'),
('SpO2', '99', '%'),
('Body Temp', '98.5', '°F'),
('BMI', '22.4', 'kg/m²');

-- 2. Appointments Table
CREATE TABLE IF NOT EXISTS public.appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor TEXT NOT NULL,
  specialty TEXT NOT NULL,
  date DATE NOT NULL,
  time TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert a future appointment so it shows up
INSERT INTO public.appointments (doctor, specialty, date, time, status) VALUES
('Dr. Priya Sharma', 'Cardiology', (NOW() + interval '5 days')::DATE, '10:00 AM', 'Confirmed'),
('Dr. Arjun Nair', 'Dermatology', (NOW() + interval '8 days')::DATE, '2:30 PM', 'Pending');

-- 3. Medicines Table
CREATE TABLE IF NOT EXISTS public.medicines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  dosage TEXT NOT NULL,
  taken BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

INSERT INTO public.medicines (name, dosage, frequency, time, taken, color) VALUES
('Metformin', '500mg', 'Twice daily', '08:00 AM', false, '#10B981'),
('Atorvastatin', '10mg', 'Once at night', '09:00 PM', true, '#4F46E5');

-- 4. Activity Log Table
CREATE TABLE IF NOT EXISTS public.activity_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,
  description TEXT NOT NULL,
  icon TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

INSERT INTO public.activity_log (action, description, icon, created_at) VALUES
('medicine_taken', 'Took Atorvastatin 10mg', 'pill', NOW() - interval '2 hours'),
('appointment_confirmed', 'Appointment with Dr. Priya confirmed', 'calendar-check', NOW() - interval '1 day'),
('record_uploaded', 'Uploaded Blood Test results', 'upload', NOW() - interval '3 days');

-- Enable RLS so the Dashboard can read it
ALTER TABLE public.vitals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medicines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for vitals" ON public.vitals FOR ALL USING (true);
CREATE POLICY "Enable all for appointments" ON public.appointments FOR ALL USING (true);
CREATE POLICY "Enable all for medicines" ON public.medicines FOR ALL USING (true);
CREATE POLICY "Enable all for activity_log" ON public.activity_log FOR ALL USING (true);
