-- Additional Supabase tables for the enhanced Dashboard
-- Run this in your Supabase SQL Editor AFTER person2_schema.sql

-- 1. Appointments table (full scheduling data)
CREATE TABLE IF NOT EXISTS public.appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor TEXT NOT NULL,
  specialty TEXT NOT NULL,
  date DATE NOT NULL,
  time TEXT NOT NULL,
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

INSERT INTO public.appointments (doctor, specialty, date, time, status) VALUES
('Dr. Priya Sharma', 'Cardiology', '2026-04-02', '10:00 AM', 'Confirmed'),
('Dr. Arjun Nair', 'Dermatology', '2026-04-05', '2:30 PM', 'Pending'),
('Dr. Lakshmi Rao', 'Neurology', '2026-04-10', '11:00 AM', 'Confirmed'),
('Dr. Rahul Mehta', 'Orthopedics', '2026-02-15', '09:00 AM', 'Completed'),
('Dr. Priya Sharma', 'Cardiology', '2025-11-20', '04:15 PM', 'Completed');

-- 2. Vitals table (health metrics tracking)
CREATE TABLE IF NOT EXISTS public.vitals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metric TEXT NOT NULL,
  value TEXT NOT NULL,
  unit TEXT NOT NULL,
  recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

INSERT INTO public.vitals (metric, value, unit, recorded_at) VALUES
('Heart Rate', '72', 'bpm', NOW() - INTERVAL '1 hour'),
('Blood Pressure', '120/80', 'mmHg', NOW() - INTERVAL '3 hours'),
('Blood Sugar', '98', 'mg/dL', NOW() - INTERVAL '6 hours'),
('SpO2', '98', '%', NOW() - INTERVAL '2 hours'),
('Body Temp', '98.4', '°F', NOW() - INTERVAL '5 hours'),
('BMI', '22.4', 'kg/m²', NOW() - INTERVAL '1 day');

-- 3. Medicines table (for medicine reminders)
CREATE TABLE IF NOT EXISTS public.medicines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  dosage TEXT,
  frequency TEXT NOT NULL,
  time TEXT NOT NULL,
  taken BOOLEAN DEFAULT FALSE,
  color TEXT DEFAULT '#4F46E5',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

INSERT INTO public.medicines (name, dosage, frequency, time, taken, color) VALUES
('Metformin', '500mg', 'Twice a day', '8:00 AM, 8:00 PM', false, '#4F46E5'),
('Atorvastatin', '10mg', 'Once a day', '9:00 PM', true, '#10B981'),
('Aspirin', '75mg', 'Once a day', '8:00 AM', false, '#F59E0B');

-- 4. Activity Log table
CREATE TABLE IF NOT EXISTS public.activity_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,
  description TEXT NOT NULL,
  icon TEXT DEFAULT 'activity',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

INSERT INTO public.activity_log (action, description, icon, created_at) VALUES
('medicine_taken', 'Took Atorvastatin 10mg', 'pill', NOW() - INTERVAL '2 hours'),
('appointment_confirmed', 'Appointment with Dr. Priya confirmed for Apr 2', 'calendar-check', NOW() - INTERVAL '1 day'),
('report_ready', 'Blood Sugar Trend report is ready', 'file-text', NOW() - INTERVAL '2 days'),
('record_uploaded', 'Uploaded Blood Test results', 'upload', NOW() - INTERVAL '3 days'),
('medicine_taken', 'Took Metformin 500mg', 'pill', NOW() - INTERVAL '3 days');
-- 5. Reports table (for health report tracking)
CREATE TABLE IF NOT EXISTS public.reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  period TEXT NOT NULL,
  status TEXT DEFAULT 'Processing',
  category TEXT DEFAULT 'General',
  trend TEXT DEFAULT 'stable',
  file_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

INSERT INTO public.reports (title, period, status, category, trend) VALUES
('Blood Sugar Trend', 'March 2026', 'Ready', 'Lab Test', 'stable'),
('Cholesterol Analysis', 'Feb 2026', 'Ready', 'Lab Test', 'down'),
('Annual Health Summary', '2025', 'Processing', 'General', 'up'),
('ECG Analysis', 'Jan 2026', 'Ready', 'Cardiac', 'stable'),
('Thyroid Panel', 'March 2026', 'Processing', 'Lab Test', 'up'),
('Vitamin D Levels', 'Feb 2026', 'Ready', 'Lab Test', 'down');

-- 6. Notifications table (for persistent alerts)
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL DEFAULT 'Reminder',
  message TEXT NOT NULL,
  time TEXT,
  read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

INSERT INTO public.notifications (type, message, time, read) VALUES
('Reminder', 'Take Metformin at 8:00 AM', '7:55 AM', false),
('Appointment', 'Appointment with Dr. Priya confirmed for Apr 2', 'Yesterday', false),
('Report', 'Your blood test report is ready', '2 days ago', true),
('Reminder', 'Take Aspirin at 8:00 AM', '3 days ago', true);

-- RLS Policies
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vitals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medicines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for appointments" ON public.appointments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for vitals" ON public.vitals FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for medicines" ON public.medicines FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for activity_log" ON public.activity_log FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for reports" ON public.reports FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for notifications" ON public.notifications FOR ALL USING (true) WITH CHECK (true);

-- NOTE: The above RLS policies allow unrestricted anonymous access.
-- For production, replace with user-based policies after implementing auth:
-- CREATE POLICY "Users can only access own data" ON public.appointments
--   FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

