-- Supabase Schema for Person 2
-- Run this directly in your Supabase SQL Editor to create all 3 tables

-- 1. Doctors Table
CREATE TABLE IF NOT EXISTS public.doctors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  specialty TEXT NOT NULL,
  rating NUMERIC,
  location TEXT,
  available BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert Mock Data for Doctors
INSERT INTO public.doctors (name, specialty, rating, location, available) VALUES
('Dr. Priya Sharma', 'Cardiology', 4.8, 'Hyderabad', true),
('Dr. Arjun Nair', 'Dermatology', 4.5, 'Bangalore', false),
('Dr. Lakshmi Rao', 'Neurology', 4.9, 'Chennai', true),
('Dr. Rahul Mehta', 'Orthopedics', 4.3, 'Mumbai', true),
('Dr. Anjali Gupta', 'Cardiology', 4.7, 'Delhi', true),
('Dr. Vikram Singh', 'Pediatrics', 4.6, 'Pune', false);


-- 2. Health Records Table
CREATE TABLE IF NOT EXISTS public.health_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  date DATE NOT NULL,
  doctor TEXT,
  file TEXT,
  file_type TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert Mock Data for Health Records
INSERT INTO public.health_records (type, date, doctor, file, file_type) VALUES
('Blood Test', '2026-03-15', 'Dr. Priya Sharma', 'blood_test_march.pdf', 'pdf'),
('X-Ray', '2026-02-10', 'Dr. Rahul Mehta', 'xray_feb.jpg', 'img'),
('ECG', '2026-01-22', 'Dr. Arjun Nair', 'ecg_jan.pdf', 'pdf');


-- 3. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER,
  blood TEXT,
  email TEXT,
  phone TEXT,
  conditions JSONB,
  allergies JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert Initial Mock Profile
INSERT INTO public.profiles (id, name, age, blood, email, phone, conditions, allergies) VALUES
(1, 'Srimannarayana Deevi', 22, 'O+', 'narayana@meditrack.app', '+91 98765 43210', '["Type 2 Diabetes", "Hypertension"]'::jsonb, '["Penicillin"]'::jsonb);

-- Enable basic RLS (Row Level Security) so anonymous API requests can read/insert
ALTER TABLE public.doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.health_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.doctors FOR SELECT USING (true);
CREATE POLICY "Enable update access for all users" ON public.doctors FOR UPDATE USING (true);

CREATE POLICY "Enable read access for all users" ON public.health_records FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.health_records FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable delete access for all users" ON public.health_records FOR DELETE USING (true);

CREATE POLICY "Enable read access for all users" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON public.profiles FOR UPDATE USING (true);
